USE EcommerceDB;

CREATE TABLE [Client] (
	ClientId INT IDENTITY (1,1) CONSTRAINT PK_Client PRIMARY KEY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Address NVARCHAR(100) NOT NULL,
);

CREATE TABLE [Product] (
	ProductId INT IDENTITY (1,1) CONSTRAINT PK_Product PRIMARY KEY NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Description NVARCHAR(100),
	Price MONEY NOT NULL,
	Quantity INT NOT NULL
)

CREATE TABLE [OrderStatus] (
	OrderStatusId INT IDENTITY (1,1) CONSTRAINT PK_OrderStatus PRIMARY KEY NOT NULL,
	Message NVARCHAR(100) NOT NULL,
)

CREATE TABLE [Order] (
	OrderId INT IDENTITY (1,1) CONSTRAINT PK_Order PRIMARY KEY NOT NULL,
	TotalPrice MONEY NOT NULL,
	Address NVARCHAR(100) NOT NULL,
	DeliveryDate DATE NOT NULL,
	ClientId INT CONSTRAINT FK_Order_ClientId FOREIGN KEY (ClientId) REFERENCES Client(ClientId)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	OrderStatusId INT CONSTRAINT FK_Order_OrderStatusId FOREIGN KEY (OrderStatusId) REFERENCES [OrderStatus](OrderStatusId)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
)

CREATE TABLE [OrderHasProduct] (
    OrderHasProductId INT IDENTITY (1,1) CONSTRAINT PK_OrderHasProduct PRIMARY KEY NOT NULL,
    Quantity INT NOT NULL,
    OrderId INT CONSTRAINT FK_OrderProduct_Order FOREIGN KEY (OrderId) REFERENCES [Order](OrderId)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    ProductId INT CONSTRAINT FK_OrderProduct_Product FOREIGN KEY (ProductId) REFERENCES Product(ProductId)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
);

